import { _electron as electron, expect } from '@playwright/test';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
const data = fs.mkdtempSync(path.join(os.tmpdir(), 'gym-qa-'));
fs.mkdirSync('recovery', { recursive: true });
const env = { ...process.env, GYM_TEST_DATA_DIR: data };
delete env.ELECTRON_RUN_AS_NODE;
let app;
let page;
const errors = [];
async function launch() {
  app = await electron.launch({ executablePath: process.env.GYM_TEST_EXECUTABLE || undefined, args: process.env.GYM_TEST_EXECUTABLE ? [] : ['.'], env });
  page = await app.firstWindow();
  page.on('pageerror', error => errors.push(error.message));
  page.on('console', message => { if (message.type() === 'error') errors.push(message.text()); });
  await page.waitForLoadState('domcontentloaded');
}
try {
  await launch();
  await expect(page.getByRole('heading', { name: 'Make it yours' })).toBeVisible();
  await page.getByLabel('Name', { exact: true }).fill('QA Tester');
  for (let i = 0; i < 3; i++) await page.getByRole('button', { name: 'Next', exact: true }).click();
  const today = new Date().getDay();
  if (![1, 3, 5].includes(today)) await page.getByRole('button', { name: ['Sun','Mon','Tue','Wed','Thu','Fri','Sat'][today], exact: true }).click();
  await page.getByRole('button', { name: 'Open the calendar', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Finish day', exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Finish day', exact: true }).click();
  await expect(page.getByText('Finish every set or skip the exercise before finishing the day.')).toBeVisible();
  expect((await page.evaluate(() => window.gym.getState())).history).toHaveLength(0);
  await page.getByRole('button', { name: 'Mark set done', exact: true }).first().click();
  await page.getByRole('button', { name: 'Learn', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Learn the map' })).toBeVisible();
  await expect.poll(() => page.locator('img').evaluateAll(images => images.every(img => img.complete && img.naturalWidth > 0))).toBe(true);
  await page.getByRole('button', { name: 'Home', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Set done', exact: true })).toHaveCount(1);
  await app.close();
  await launch();
  await expect(page.getByRole('button', { name: 'Set done', exact: true })).toHaveCount(1);
  const finish = page.getByRole('button', { name: 'Finish exercise', exact: true });
  while (await finish.count()) await finish.first().click();
  await page.getByRole('button', { name: 'Undo finish', exact: true }).first().click();
  await expect(page.getByRole('button', { name: 'Mark set done', exact: true })).toHaveCount(3);
  await finish.first().click();
  await page.getByRole('button', { name: 'Finish day', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Finish day', exact: true })).toHaveCount(0);
  let state = await page.evaluate(() => window.gym.getState());
  expect(state.history).toHaveLength(1);
  expect(state.queue.nextIndex).toBe(1);
  expect(state.lifts['chest-press'].workingKg).toBe(20);
  await page.getByRole('button', { name: 'Log', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Weights & room' })).toBeVisible();
  await page.getByLabel('Weight kg', { exact: true }).fill('-1');
  await page.getByLabel('Height cm', { exact: true }).click();
  await expect(page.getByRole('alert')).toContainText('Body weight must be between');
  expect((await page.evaluate(() => window.gym.getState())).profile.weightKg).toBe(60);
  await page.getByRole('button', { name: 'Dismiss' }).click();
  await page.getByLabel('Weight kg', { exact: true }).fill('72');
  await page.getByLabel('Height cm', { exact: true }).click();
  await expect.poll(async () => (await page.evaluate(() => window.gym.getState())).profile.weightKg).toBe(72);
  await page.getByText('Optional email', { exact: true }).click();
  await page.getByRole('button', { name: 'Send test', exact: true }).click();
  await expect(page.getByText('Add a Gmail address and app password in Log → Optional email first.', { exact: true })).toBeVisible();
  await page.getByLabel('Gmail', { exact: true }).fill('qa@example.com');
  await page.getByLabel('App password', { exact: true }).fill('abcdefghijklmnop');
  await page.getByRole('button', { name: 'Save', exact: true }).click();
  await expect(page.getByText('Saved on this PC only.', { exact: true })).toBeVisible();
  const saved = JSON.parse(fs.readFileSync(path.join(data, 'gym-state.json'), 'utf8'));
  expect(saved.smtp.encryptedPassword).toBeTruthy();
  expect(saved.smtp.appPassword).toBeUndefined();
  if (!process.env.GYM_TEST_EXECUTABLE) await page.screenshot({ path: 'recovery/qa-log.png' });
  await app.close();
  await launch();
  state = await page.evaluate(() => window.gym.getState());
  expect(state.history).toHaveLength(1);
  expect(state.queue.nextIndex).toBe(1);
  expect(state.smtp.appPassword).toBe('abcdefghijklmnop');
  await page.getByRole('button', { name: 'Program', exact: true }).click();
  await page.getByRole('button', { name: /Upper \/ Lower \/ Legs/ }).click();
  await expect.poll(async () => (await page.evaluate(() => window.gym.getState())).profile.program).toBe('ull');
  await page.getByRole('button', { name: 'Home', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Chest + Triceps', exact: true })).toBeVisible();
  await expect(page.getByText('Logged reps: 12 / 12 / 12', { exact: true })).toHaveCount(5);
  await expect(page.getByRole('button', { name: 'Finish day', exact: true })).toHaveCount(0);
  if (!process.env.GYM_TEST_EXECUTABLE) await page.screenshot({ path: 'recovery/qa-home.png' });
  expect(fs.existsSync(path.join(data, 'gym-state.json.backup'))).toBe(true);
  expect(errors).toEqual([]);
  console.log('PASS: Electron onboarding, unfinished-set guard, anatomy assets, navigation/restart drafts, undo, completion, progression, email setup errors and persistent history.');
} catch (error) {
  console.error(error);
  if (page) { console.error(await page.locator('body').innerText().catch(() => 'No page')); await page.screenshot({ path: 'recovery/qa-failure.png' }).catch(() => {}); }
  console.error('Renderer errors:', errors);
  process.exitCode = 1;
} finally {
  await app?.close().catch(() => {});
  console.log(`Isolated test data: ${data}`);
}
